[versions]
androidGradlePlugin = "8.2.1"
androidxActivity = "1.9.0-alpha01"
androidxAnnotations = "1.8.2"
androidxBenchmark = "1.2.2"
androidxCore = "1.13.0-alpha03"
androidxDatastore = "1.1.0-beta01"
androidxLifecycle = "2.7.0"
androidxNavigation = "2.7.6"
androidxPaging = "3.3.0-alpha02"
androidxSplashscreen = "1.1.0-alpha02"
androidxStartup = "1.2.0-alpha02"
androidxTestCore = "1.6.0-alpha04"
androidxTestJunit = "1.2.0-alpha02"
androidxTestRules = "1.6.0-alpha02"
androidxTestRunner = "1.6.0-alpha05"
androidxTestUiAutomator = "2.3.0-beta01"
androidxTracing = "1.3.0-alpha02"
androidxWindow = "1.2.0"
baselineProfilePlugin = "1.2.2"
composeBom = "2024.01.00-alpha01"
composeCompiler = "1.5.8"
coroutines = "1.7.3"
detekt = "1.23.4"
detektCompose = "0.3.10"
espresso = "3.6.0-alpha02"
hilt = "2.50"
hiltNavigation = "1.2.0-alpha01"
kotlin = "1.9.22"
multidex = "2.0.1"
okhttp = "5.0.0-alpha.12"
profileinstallerVersion = "1.3.1"

[libraries]
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity"}
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotations"}
androidx-benchmark-micro = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "androidxBenchmark"}
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxBenchmark"}
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore"}
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastore"}
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle"}
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle"}
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation"}
androidx-navigation-test = { group = "androidx.navigation", name = "navigation-testing-ktx", version.ref = "androidxNavigation"}
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging"}
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "androidxPaging"}
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "androidxPaging"}
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashscreen"}
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup"}
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore"}
androidx-test-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestJunit"}
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules"}
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner"}
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxTestUiAutomator"}
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "androidxTracing"}
androidx-window = { module = "androidx.window:window", version.ref = "androidxWindow"}
detekt-rules-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose"}
detekt-rules-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt"}
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso"}
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso"}
espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso"}
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation"}
hilt-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt"}
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstallerVersion" }

[plugins]
android-app = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baseline-profile = { id = "androidx.baselineprofile", version.ref = "baselineProfilePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
